### ISSUE TITLE
工程中存在公司内部服务相关配置

### ISSUE THREAD

**Issue by yinggaozhen** [didi/ES-Fastloader#1]
譬如存在Odin相关配置
- [https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/alarm/AlarmUtil.java#L39](https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/alarm/AlarmUtil.java#L39)
- [https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/utils/Constants.java#L34](https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/utils/Constants.java#L34)

另外似乎还包含了公司内部一些服务地址和端口，如 : 
- [https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/utils/Constants.java#L27](https://github.com/didi/ES-Fastloader/blob/master/src/main/java/com/didi/bigdata/mr2es/utils/Constants.java#L27)

**Comment by lynchlee** [comment]
开源项目还是需要要认真的规划。

**Comment by jokerZH** [comment]
已经发布最新版代码，删除了相关文件
