### ISSUE TITLE
请教一个问题，关于nodemanager端本地生成的lucene文件加载到es本地节点之后的操作

### ISSUE THREAD

**Issue by a129734** [didi/ES-Fastloader#11]
您好，我们的业务场景和滴滴的稍有不同，感觉会简单些
暂时我们不会有更新索引的场景，而是每天都新建一份索引，全量刷写数据
我想问下，hadoop fs -get已经把文件按照shard对应关系拉取到es集群本地的节点了
后面如何把lucene的各个文件加载到es集群呢，相当于把这个部分数据加载到一个空索引里面，我理解就是让文件和索引在es端对应起来，不知道这个步骤直接把文件放进索引的存储目录行不行~
还是说要调取lucene的indexWriter这种操作呢，多谢

**Comment by jokerZH** [comment]
除了使用lucene的indexWriter，还有一种办法把lucene文件加入到一个空的shard，步骤如下
1. 将索引close
2. 删除shard中原先的lucene目录和translog目录
3. 将lucene文件和translog文件拷贝到shard对应的目录中
4.将索引open，就可以查询了

不过上面的方法有个问题，close和open的操作需要经过master，很容易对master造成压力，任务数较多的情况下，会出现master处理不过来的情况

**Comment by a129734** [comment]
试了一下，好像有点问题，还得再请教一下，看看是不是我哪里没理解对~
我的测试索引共有2个分片，我在reduce端启动了2个task，通过map端的路由，把所有数据分成了2份，第一个reduce写入到本地启动的es之后，文件中有2个分片，分片0有数据，分片1是空的，第二个reduce是分片1有数据，分片0是空的。
1、在线上es集群新建一个索引(无副本)，关闭索引，通过查询获知新索引的2个分片所在机器
2、把数据从hdfs下载到线上es集群的2个节点上，解压。
3、把第一个reduce的0分片中的index和translog拷贝到0分片所在的机器目录下，此reduce的1分片数据未操作
4、把第二个reduce的1分片中的index和translog拷贝到1分片所在的机器目录下，此reduce的0分片数据未操作
5、打开索引
6、查询过程中发现总条目数争取，但是查询明细的时候总有一个shard报错。。。。
"reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
类似上面的错误信息
