### ISSUE TITLE
Failed to execute goal on project mr2es

### ISSUE THREAD

**Issue by lynchlee** [didi/ES-Fastloader#2]
master:  mvn clean package -Dmaven.test.skip=true -Ppro

[ERROR] Failed to execute goal on project mr2es: Could not resolve dependencies for project com.didi.bigdata:mr2es:jar:1.0.0: Could not find artifact org.apache.hadoop:hadoop-client:jar:2.7.2-2312 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by lynchlee** [comment]
branch master

**Comment by zhangliangboy** [comment]
you can try https://github.com/didi/ES-Fastloader/tree/1.0.0

**Comment by jokerZH** [comment]
go to mr directory, and run mvn clean package -Dmaven.test.skip
