### ISSUE TITLE
es高级版本不能routing算法不能再用2.X的代码了

### ISSUE THREAD

**Issue by goodqinjin** [didi/ES-Fastloader#9]
这里给出ES7.X的代码：
int routingNumShards=MetaDataCreateIndexService.calculateNumRoutingShards(numShards, Version.CURRENT);
int routingFactor = routingNumShards / numShards;

int shardId = Math.floorMod(hash, routingNumShards) / routingFactor;

希望能有所帮助

**Comment by jokerZH** [comment]
感谢，我们接下来也要升级到7.x版本了

**Comment by dyhyao6** [comment]
我看plugin 模块相关的类在es6 和es7.x中都有所变化，请问如何升级到es7呢？谢谢 @goodqinjin @jokerZH
